export const AUTH_REQUEST = 'AUTH_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// Users
export const USER_REQUEST = 'USER_REQUEST';
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const GET_USERS = 'GET_USERS';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAIL = 'USERS_FAIL';

// Activities
export const ACTIVITY_REQUEST = 'ACTIVITY_REQUEST';
export const ACTIVITY_UPDATE_REQUEST = 'ACTIVITY_UPDATE_REQUEST';
export const ACTIVITY_DELETE_REQUEST = 'ACTIVITY_DELETE_REQUEST';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const ACTIVITY_SUCCESS = 'ACTIVITY_SUCCESS';
export const ACTIVITY_FAIL = 'ACTIVITY_FAIL';

// People
export const PEOPLE_REQUEST = 'PEOPLE_REQUEST';
export const PEOPLE_UPDATE_REQUEST = 'PEOPLE_UPDATE_REQUEST';
export const GET_PEOPLE = 'GET_PEOPLE';
export const PEOPLE_SUCCESS = 'PEOPLE_SUCCESS';
export const PEOPLE_FAIL = 'PEOPLE_FAIL';

// Lines
export const LINES_REQUEST = 'LINES_REQUEST';
export const LINES_UPDATE_REQUEST = 'LINES_UPDATE_REQUEST';
export const LINES_DELETE_REQUEST = 'LINES_DELETE_REQUEST';
export const GET_LINES = 'GET_LINES';
export const LINES_SUCCESS = 'LINES_SUCCESS';
export const LINES_FAIL = 'LINES_FAIL';

//Import
export const GET_CARREES = 'GET_CARREES';
export const INSERT_INFO_ESTUDIANTES = 'INSERT_INFO_ESTUDIANTES';
export const INSERT_INFO_DOCENTES = 'INSERT_INFO_DOCENTES';
export const INSERT_INFO_PERSONAL = 'INSERT_INFO_PERSONAL';
export const INSERT_INFO_CARRERAS = 'INSERT_INFO_CARRERAS';
export const INSERT_SUCCESS = 'INSERT_SUCCESS';
export const INSERT_FAIL = 'INSERT_FAIL';

//Asesoria
export const ASESORIA_REQUEST = 'ASESORIA_REQUEST';
export const ASESORIA_UPDATE_REQUEST = 'ASESORIA_UPDATE_REQUEST';
export const GET_ASESORIA = 'GET_ASESORIA';
export const ASESORIA_SUCCESS = 'ASESORIA_SUCCESS';
export const ASESORIA_FAIL = 'ASESORIA_FAIL';

//Informe
export const INFORME_REQUEST = 'INFORME_REQUEST';
export const INFORME_SUCCESS = 'INFORME_SUCCESS';
export const INFORME_FAIL = 'INFORME_FAIL';